### ISSUE TITLE
Issues using this task

### ISSUE THREAD

**Issue by vote539** [miniflycn/grunt-compassn#1]
Thanks for making this Grunt task; it has great potential for situations when it's not possible to install a Ruby runtime for Compass proper.

There were a few issues I ran into while trying to use this task.
1. The README looks like it's been copied from _grunt-contrib-compass_; I think you missed a few places where you need to change the text.  For example, where it says `npm install grunt-contrib-compass --save-dev` it should of course say `npm install grunt-compassn --save-dev`
2. The "usage example" section down at the bottom does not appear to be consistent with the requirements for this Grunt task.  In particular, it appears that the user needs to specify the "files" hash, rather than specifying `sassDir` and `cssDir` as in the official _grunt-contrib-compass_.

Also, once I got the task to run, all of my CSS output files contained the string "[object Object]" instead of any compiled CSS code.

**Comment by miniflycn** [comment]
I' m sorry for this.
`compass-node`'s API has been changed for a lone time, but i forget to fixed it.
Please update to 0.2.1, and you will get the right result.

**Comment by vote539** [comment]
Nice, thanks for the ultra fast fix :sunglasses: I'm now getting real CSS in the output files.

There is one file I have which is not creating a corresponding output file.  There might be something in that file that is not being recognized by compass-node.  Is there a way to see compass-node's error log?

**Comment by vote539** [comment]
To clarify, there is a line in the console output that looks like this:

```
Running "compass:dev" (compass) task
File "app/css/sanscon.css" created.
File "app/css/print.css" created.
>> [object Object]
File "app/css/util.css" created.
File "app/css/popover.css" created.
```

Perhaps the line in the middle `>> [object Object]` is the error object that needs to be parsed out and printed.

**Comment by vote539** [comment]
The PR I just made fixes the above issue such that SASS compile errors are shown on the command line after running Grunt.
